# Generated by Django 4.2 on 2023-04-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_category_is_active'),
        ('users', '0002_remove_token_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.category'),
        ),
    ]
