# Generated by Django 4.1.8 on 2023-04-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cart_payments_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
