# Generated by Django 4.1.8 on 2023-04-15 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='cart_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='users.token'),
        ),
    ]
