# Generated by Django 4.2 on 2023-04-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='token_id',
        ),
    ]
